### ISSUE TITLE
No metadata is present in the term document matrix with Topic Model

### ISSUE THREAD

**Issue by MastafaF** [JasonKessler/scattertext#67]
Hi, 

I am replicating line by line the example with Topic List of words from **demo_word_list_topic_model.py** . 

Here is the error message in python: 
```bash 
Traceback (most recent call last):
  File "demo_word_topic_list_model.py", line 27, in <module>
    html = st.produce_scattertext_explorer(
  File "C:\Users\xxxxxxxx\anaconda3\envs\xxxxxxx\lib\site-packages\scattertext\__init__.py", line 487, in produce_scattertext_explorer
    scatter_chart_explorer.inject_metadata_term_lists(topic_model_term_lists)
  File "C:\Users\xxxxxxxx\anaconda3\envs\xxxxxxxx\lib\site-packages\scattertext\ScatterChart.py", line 104, in inject_metadata_term_lists
    raise TermDocMatrixHasNoMetadataException("No metadata is present in the term document matrix")
scattertext.ScatterChart.TermDocMatrixHasNoMetadataException: No metadata is present in the term document matrix

```

## Your Environment

* Operating System: Windows 64 bits 
* Python Version Used: Python 3.8.5
* Scattertext Version Used: scattertext==0.0.2.67
* Environment Information: ???

**Comment by JasonKessler** [comment]
I'm pushing a new version, 0.0.2.68 which should correct this issue. Please update your version and try again.

**Comment by MastafaF** [comment]
Works great now, thanks!!
